# Change these first
owner: IDR # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: IDR
    url: https://idr.openmicroscopy.org
  - name: ITR
    url: https://itr.openmicroscopy.org
  - name: IDR API
    url: https://idr.openmicroscopy.org/about/api.html
  - name: IDR submission
    url: https://idr.openmicroscopy.org/about/submission.html
  - name: IDR Analysis
    url: https://idr-analysis.openmicroscopy.org
  - name: IDR Jupyter
    url: https://idr.openmicroscopy.org/jupyter
  - name: IDR (well 590686)
    url: https://idr.openmicroscopy.org/webclient/?show=well-590686
  - name: IDR (well 119093)
    url: https://idr.openmicroscopy.org/webclient/?show=well-119093
  - name: IDR (image 648950)
    url: https://idr.openmicroscopy.org/webclient/?show=image-648950
  - name: IDR (dataset 61)
    url: https://idr.openmicroscopy.org/webclient/?show=dataset-61
  - name: IDR (phenotype CMPO_0000393)
    url: https://idr.openmicroscopy.org/mapr/phenotype/?value=CMPO_0000393
  - name: IDR (gene SGOL1)
    url: https://idr.openmicroscopy.org/mapr/gene/?value=SGOL1
  - name: idr0054 sample image
    url: https://idr.openmicroscopy.org/webgateway/render_image/5025551/0/0/?c=1|0:150$FF0000&m=c
  - name: idr0054 sample image
    url: https://idr.openmicroscopy.org/webgateway/render_image/5025551/0/0/?c=1|0:150$FF0000&m=c
  - name: IDR OME-NGFF sample plate
    url: https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/.zattrs
  - name: IDR tracking system
    url: $IDR_REDMINE

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ome/www.openmicroscopy.org/master/img/logos/idr-logo.svg
  name: IDR status
  introTitle: "Welcome to the status page of IDR."
  introMessage: Contact IDR on the [image.sc](https://forum.image.sc/tag/idr) forum or [Twitter](https://twitter.com/IDRnews) to report issues
  navbar:
    - title: OME Status
      href: https://ome.github.io/upptime/
    - title: GitHub Status
      href: https://www.githubstatus.com/
    - title: GitHub repository
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
